### PR TITLE
feat(cdp-analytics-node): add support Vercel Edge

### PR DESCRIPTION
**Pull request by ValentinH**
This is porting [this PR from the upstream](https://github.com/segmentio/analytics-next/pull/813) in order to have this lib run fine in the Vercel Edge Runtime.

Indeed, we are currently in the process of moving from Segment to Customer.io DP and this is a blocker for us as all our tracking code is running on the Edge Runtime.
With the current version, there is no error whatsoever but events are never reaching customer.io 😭

### CODE REVIEW

**Review by nunofgs — APPROVED** [review]
Fantastic, thank you. I added a missing condition from upstream but was able to test this successfully in a Vercel app.

**Comment by ValentinH** [comment]
> Fantastic, thank you. I added a missing condition from upstream but was able to test this successfully in a Vercel app.

@nunofgs I actually removed that part because it was not present anymore on the latest version. 
Also I don't know if you noticed but not only the check was removed, the used property has also changed.

FWIW we are running the code from this PR in production and it runs fine.

**Comment by nunofgs** [comment]
Glad to hear! I saw a crash on that line when I was testing but I'll be sure to evaluate once we bring in the latest changes.

Thanks again!

**Comment by ValentinH** [comment]
When do you think a new version could be released so that we can use this change please?

**Comment by nunofgs** [comment]
It’s already out :)

https://www.npmjs.com/package/@customerio/cdp-analytics-node

**Comment by ValentinH** [comment]
Oh great! I was checking the package.json version field on GitHub.

**Pull request merged**
